!IFDEF UNICODE
OPT_UNICODE=/D_UNICODE
!ENDIF

# zlib.lib uses /MD, so we must as well.
CFLAGS=/O2 /MD $(OPT_UNICODE)

all: fsh2png.exe

static: fsh2png-static.exe

fsh2png.exe: fsh2png.c
	CL $(CFLAGS) /DPNG_USE_DLL libpng16.lib $** /Fe$@

fsh2png-static.exe: fsh2png.c
	CL $(CFLAGS) $** libpng.lib zlib.lib /Fe$@

clean:
	DEL fsh2png.exe fsh2png-static.exe
